<template>
  <div class="custom-loader">
    <div class="loadingio-spinner-pulse-zq7jfr5p9q9">
      <div class="ldio-byvcar7bpnm">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<style type="text/css">
@keyframes ldio-byvcar7bpnm-1 {
  0% {
    top: 36px;
    height: 128px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-byvcar7bpnm-2 {
  0% {
    top: 41.99999999999999px;
    height: 116.00000000000001px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-byvcar7bpnm-3 {
  0% {
    top: 48px;
    height: 104px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
.ldio-byvcar7bpnm div {
  position: absolute;
  width: 30px;
}
.ldio-byvcar7bpnm div:nth-child(1) {
  left: 35px;
  background: #157759;
  animation: ldio-byvcar7bpnm-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s;
}
.ldio-byvcar7bpnm div:nth-child(2) {
  left: 85px;
  background: #53ab8b;
  animation: ldio-byvcar7bpnm-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s;
}
.ldio-byvcar7bpnm div:nth-child(3) {
  left: 135px;
  background: #82dbb8;
  animation: ldio-byvcar7bpnm-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-zq7jfr5p9q9 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-byvcar7bpnm {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-byvcar7bpnm div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>

<script>
export default {
  name: 'CustomLoader',
};
</script>
